Dockerfile
cmd/placement/main.go
pkg/controllers/manager.go
pkg/controllers/placement/controller.go
pkg/controllers/placement/controller_test.go

add missing files

---

deploy/hub/deployment.yaml
pkg/controllers/manager.go
pkg/controllers/scheduling/cluster_event_handler.go
pkg/controllers/scheduling/cluster_event_handler_test.go
pkg/controllers/scheduling/clusterset_event_handler.go
pkg/controllers/scheduling/clusterset_event_handler_test.go
pkg/controllers/scheduling/clustersetbinding_event_handler.go
pkg/controllers/scheduling/clustersetbinding_event_handler_test.go
pkg/controllers/scheduling/schedule.go
pkg/controllers/scheduling/scheduling_controller.go
pkg/controllers/scheduling/scheduling_controller_test.go
pkg/helpers/testing/builders.go
test/e2e/placement_test.go
test/integration/placement_test.go

The related task: https://github.com/open-cluster-management/backlog/issues/12422

reschedule once cluster/clusterset/clustersetbinding changes

---

pkg/controllers/scheduling/schedule.go
pkg/controllers/scheduling/schedule_test.go
test/integration/placement_test.go

The related task: https://github.com/open-cluster-management/backlog/issues/13055

support multiple placementdecisions

---

pkg/controllers/scheduling/schedule.go
pkg/controllers/scheduling/schedule_test.go
pkg/controllers/scheduling/scheduling_controller.go
pkg/controllers/scheduling/scheduling_controller_test.go

The related issue: https://github.com/open-cluster-management/backlog/issues/13120

add more condition reasons

---

.github/workflows/go-presubmit.yml
CONTRIBUTING.md
Makefile
README.md

update readme & makefile

---

.github/workflows/go-postsubmit.yml
.github/workflows/go-presubmit.yml
.github/workflows/go-release.yml
.gitignore
CHANGELOG/CHANGELOG-v0.1.md

Signed-off-by: Zhiwei Yin <zyin@redhat.com>

add release action job

---

deploy/hub/clusterrole.yaml
test/e2e/placement_test.go
test/integration/util/util.go

add one more e2e test case

---

README.md

- add lost step to install dependency. Keep it consistent version with contribution document.
- here document is concise and quick in creating a resource. File is more suitable for later reuse. I propose to use here document.

update document to make it more friendly in first try

---

go.mod
go.sum
pkg/controllers/manager.go
pkg/controllers/scheduling/schedule.go
pkg/controllers/scheduling/schedule_test.go
pkg/controllers/scheduling/scheduling_controller.go
pkg/controllers/scheduling/scheduling_controller_test.go
pkg/debugger/debugger.go
pkg/debugger/debugger_test.go
pkg/helpers/testing/helpers.go
pkg/plugins/balance/balance.go
pkg/plugins/balance/balance_test.go
pkg/plugins/interface.go
pkg/plugins/predicate/predicate.go
pkg/plugins/predicate/predicate_test.go
pkg/plugins/steady/steady.go
pkg/plugins/steady/steady_test.go
vendor/modules.txt

Signed-off-by: Jian Qiu <jqiu@redhat.com>

Use plugin to support steady/balance

---

pkg/controllers/scheduling/schedule.go
pkg/controllers/scheduling/schedule_test.go
pkg/helpers/testing/builders.go
pkg/plugins/resource/resource.go
pkg/plugins/resource/resource_test.go
test/integration/placement_test.go

Ref: https://github.com/open-cluster-management/backlog/issues/15599

add resource based scheduling prioritizer

---

CONTRIBUTING.md
test/scalability/README.md

Signed-off-by: suigh <suigh@cn.ibm.com>
Add doc for scalability test (#44, #41)

add doc for scalability test

---

test/scalability/placement_test.go

Signed-off-by: suigh <suigh@cn.ibm.com>
Merge following two functions into one as they will get all the placements from api-server with same logic and do some checks, when there are hundreds of placements, the impact on api-server is big. Merge them into one to reduce the impact on api-server.
assertPlacementDecisionCreated
assertNumberOfDecisions

merge functions for performance of scalability test

---

CHANGELOG/CHANGELOG-v0.3.md
CHANGELOG/README.md

add changelog for v0.3

---

pkg/controllers/manager.go
pkg/controllers/scheduling/schedule.go
pkg/controllers/scheduling/scheduling_controller.go
pkg/debugger/debugger_test.go
pkg/helpers/testing/helpers.go
pkg/plugins/addon/addon.go
pkg/plugins/addon/addon_test.go
pkg/plugins/balance/balance.go
pkg/plugins/balance/balance_test.go
pkg/plugins/interface.go
pkg/plugins/predicate/predicate.go
pkg/plugins/predicate/predicate_test.go
pkg/plugins/resource/resource.go
pkg/plugins/resource/resource_test.go
pkg/plugins/steady/steady.go
pkg/plugins/steady/steady_test.go
pkg/plugins/tainttoleration/taint_toleration.go
pkg/plugins/tainttoleration/taint_toleration_test.go
test/integration/placement_test.go

Ref:
https://github.com/stolostron/backlog/issues/20179
https://github.com/open-cluster-management-io/community/issues/48
This PR is based on [proposal 20-taint-toleration](https://github.com/open-cluster-management-io/enhancements/tree/main/enhancements/sig-architecture/20-taint-toleration)
- cover the case when the toleration has TolerationSeconds
- requeue placement when toleration seconds expire

requeue placement when toleration seconds expire 

---

.github/workflows/go-postsubmit.yml

Signed-off-by: Jian Qiu <jqiu@redhat.com>

Avoid building latest image in release branch

---

pkg/plugins/tainttoleration/taint_toleration_test.go

Adding below 6 kinds of UT:
- taint.Effect is NoSelect, testing tolerations with different operator and key/value
- taint.Effect is NoSelectIfNew, testing tolerations with differet key/value, and cluster is/not in decision
- taint.Effect is PreferNoSelect, testing tolerations with differet key/value
- multiple taints and tolerations
- testing effect matches
- testing TolerationSeconds

add more UT for taints/tolerations

---

CHANGELOG/CHANGELOG-v0.4.md

add changelog for v0.4

---

Dockerfile

Update golang builder in Dockerfile

---

README.md

Signed-off-by: xuezhaojun <zxue@redhat.com>

Lint readme markdown

---

CHANGELOG/CHANGELOG-v0.8.md

add changelog for v0.8

---

pkg/controllers/scheduling/cluster_event_handler.go
pkg/controllers/scheduling/cluster_event_handler_test.go
pkg/controllers/scheduling/clusterset_event_handler_test.go
test/e2e/placement_test.go
test/integration/placement_test.go

trigger sync when cluster belongs to LabelSelector type clusterset 

---

CHANGELOG/CHANGELOG-v0.9.md

add changelog for v0.9

---

.github/workflows/go-postsubmit.yml
.github/workflows/go-presubmit.yml
.github/workflows/go-release.yml
Dockerfile
go.mod

Upgrade golang to 1.19

---

test/integration/assertion_test.go
test/integration/placement_test.go
test/integration/prioritizer_test.go
test/integration/toleration_test.go

Signed-off-by: Jian Qiu <jqiu@redhat.com>

Refactor integration test

---

pkg/controllers/framework/interface.go
pkg/controllers/scheduling/schedule.go
pkg/controllers/scheduling/scheduling_controller.go
pkg/plugins/balance/balance.go
pkg/plugins/interface.go
test/e2e/placement_test.go
test/integration/assertion_test.go
test/integration/placement_test.go
test/integration/prioritizer_test.go

Signed-off-by: zhujian <jiazhu@redhat.com>

Add integration tests

---

.github/workflows/go-postsubmit.yml
.github/workflows/go-presubmit.yml
.github/workflows/go-release.yml

Signed-off-by: ycyaoxdu <yaoyuchen0626@163.com>

upgrade github action

---

.github/workflows/go-postsubmit.yml
.github/workflows/go-presubmit.yml
CHANGELOG/CHANGELOG-v0.10.md

add changelog for v0.10.0
